import os
import numpy as np

# IMPOSTAZIONI GENERALI
SEME = 42  
ALTEZZA_IMG = 256 # Scelta a 256 per non perdere le texture spaziali 
LARGHEZZA_IMG = 256
DIMENSIONE_LOTTO = 32
MEDIA_IMAGENET = np.array([123.68, 116.779, 103.939], dtype=np.float32)

#  PERCORSI CARTELLE
CARTELLA_PROGETTO = os.path.dirname(os.path.abspath(__file__))

CARTELLA_GREZZA_AID = os.path.join(CARTELLA_PROGETTO, "AID")
CARTELLA_GREZZA_UCM = os.path.join(CARTELLA_PROGETTO, "UCMerced_LandUse", "Images")

CARTELLA_BASE_DIVISIONE = os.path.join(CARTELLA_PROGETTO, "dati_divisi")
CARTELLA_DIV_AID = os.path.join(CARTELLA_BASE_DIVISIONE, "AID")
CARTELLA_DIV_UCM = os.path.join(CARTELLA_BASE_DIVISIONE, "UCMerced")

# CLASSI E PERCENTUALI DI DIVISIONE
CLASSI_AID = 30 
CLASSI_UCM = 21 

RAPPORTO_ADD_UCM = 0.70
RAPPORTO_VAL_UCM = 0.15
RAPPORTO_TEST_UCM = 0.15

RAPPORTO_ADD_AID = 0.70
RAPPORTO_VAL_AID = 0.30